/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package UserInterface.workArea.Student;

import Business.Course.StudentCourseStatus;
import Business.Course.StudentCourses;
import Business.UserAccounts.UserAccount;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author anusreemohanan
 */
public class StudentRequestGraduationJPanel extends javax.swing.JPanel {
    JPanel workAreaPanel;
    UserAccount userAccount;
    StudentCourses studentCourses;

    /**
     * Creates new form StudentRequestGraduationJPanel
     */

    StudentRequestGraduationJPanel(JPanel workAreaPanel, UserAccount userAccount, StudentCourses studentCourses) {
        initComponents();
        this.workAreaPanel = workAreaPanel;
        this.userAccount = userAccount;
        this.studentCourses = studentCourses;
        populateTable(studentCourses);
    }
    private void populateTable(StudentCourses studentCourses) {
       DefaultTableModel dtm = (DefaultTableModel) tblGradesheet.getModel();
       dtm.setRowCount(0);
       for(StudentCourseStatus studentCourseStatus: studentCourses.getStudentCourses()){
                Object row[]= new Object[3];
                row[0] = studentCourseStatus.getStudentBrowseCourses().getCourseSemester();
                row[1] = studentCourseStatus.getStudentBrowseCourses().getCourseSemester().getCourse().getCourseName();
                row[2] = studentCourseStatus;
                dtm.addRow(row);         
       }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblGraduationTranscripts = new javax.swing.JLabel();
        tblGradesheetPanel = new javax.swing.JScrollPane();
        tblGradesheet = new javax.swing.JTable();
        lblStatement = new javax.swing.JLabel();
        lblCredits = new javax.swing.JLabel();

        setBackground(new java.awt.Color(51, 153, 255));

        lblGraduationTranscripts.setFont(new java.awt.Font("Lucida Grande", 1, 18)); // NOI18N
        lblGraduationTranscripts.setForeground(new java.awt.Color(255, 255, 255));
        lblGraduationTranscripts.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblGraduationTranscripts.setText("Graduation Transcript");

        tblGradesheet.setFont(new java.awt.Font("Lucida Grande", 0, 13)); // NOI18N
        tblGradesheet.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Course ID", "Course Name"
            }
        ));
        tblGradesheetPanel.setViewportView(tblGradesheet);

        lblStatement.setFont(new java.awt.Font("Lucida Grande", 3, 14)); // NOI18N
        lblStatement.setForeground(new java.awt.Color(255, 255, 255));
        lblStatement.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblStatement.setText("Congratulations ! You have Graduated !");
        lblStatement.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 1, true));

        lblCredits.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
        lblCredits.setForeground(new java.awt.Color(255, 255, 255));
        lblCredits.setText("Credits Received: 8 Credits");
        lblCredits.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblGraduationTranscripts, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(104, 104, 104)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblStatement, javax.swing.GroupLayout.PREFERRED_SIZE, 291, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(lblCredits))
                    .addComponent(tblGradesheetPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 502, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(102, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(lblGraduationTranscripts, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(tblGradesheetPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 355, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblStatement, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblCredits, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(107, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel lblCredits;
    private javax.swing.JLabel lblGraduationTranscripts;
    private javax.swing.JLabel lblStatement;
    private javax.swing.JTable tblGradesheet;
    private javax.swing.JScrollPane tblGradesheetPanel;
    // End of variables declaration//GEN-END:variables
}
