/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package UserInterface;

import Business.Business;
import Business.Course.CourseDirectory;
import Business.Profiles.ProfessorProfile;
import Business.Profiles.Profile;
import Business.UserAccounts.UserAccount;
import Business.UserAccounts.UserAccountDirectory;
import Business.workArea.Admin.AdminWorkAreaJPanel;
import UserInterface.workArea.NewUsers.ProfessorRegistrationJPanel;
import UserInterface.workArea.NewUsers.StudentRegistrationJPanel;
import UserInterface.workArea.Professor.ProfessorWorkAreaJPanel;
import UserInterface.workArea.Student.StudentWorkAreaJPanel;
import java.awt.CardLayout;
import javax.swing.JOptionPane;

/**
 *
 * @author Darshil Shah
 */

public class ProfileWorkAreaMainJFrame extends javax.swing.JFrame {

    /**
     * Creates new form ProfileWorkAreaMainJFrame
     */
    Business business;
    public ProfileWorkAreaMainJFrame() {
        initComponents();
        business = ConfigureBusiness.initialize();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        SplitHomeArea = new javax.swing.JSplitPane();
        ActionPanel = new javax.swing.JPanel();
        txtUserName = new javax.swing.JTextField();
        lblUserName = new javax.swing.JLabel();
        lblPassword = new javax.swing.JLabel();
        lblLogin = new javax.swing.JLabel();
        btnLogin = new javax.swing.JButton();
        lblNewProfessor = new javax.swing.JLabel();
        btnProfessorRegistration = new javax.swing.JButton();
        btnStudentSignup = new javax.swing.JButton();
        lblNewStudent = new javax.swing.JLabel();
        lblSignUp = new javax.swing.JLabel();
        txtPassword = new javax.swing.JPasswordField();
        workAreaPanel = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        SplitHomeArea.setBackground(new java.awt.Color(102, 153, 255));

        ActionPanel.setBackground(new java.awt.Color(51, 204, 255));

        txtUserName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtUserNameActionPerformed(evt);
            }
        });

        lblUserName.setFont(new java.awt.Font("Lucida Grande", 0, 13)); // NOI18N
        lblUserName.setForeground(new java.awt.Color(255, 255, 255));
        lblUserName.setText("Username");

        lblPassword.setFont(new java.awt.Font("Lucida Grande", 0, 13)); // NOI18N
        lblPassword.setForeground(new java.awt.Color(255, 255, 255));
        lblPassword.setText("Pasword");

        lblLogin.setFont(new java.awt.Font("Lucida Grande", 1, 18)); // NOI18N
        lblLogin.setForeground(new java.awt.Color(255, 255, 255));
        lblLogin.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblLogin.setText("Login");

        btnLogin.setFont(new java.awt.Font("Lucida Grande", 0, 13)); // NOI18N
        btnLogin.setText("Login");
        btnLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLoginActionPerformed(evt);
            }
        });

        lblNewProfessor.setFont(new java.awt.Font("Lucida Grande", 0, 13)); // NOI18N
        lblNewProfessor.setForeground(new java.awt.Color(255, 255, 255));
        lblNewProfessor.setText("New Professor");

        btnProfessorRegistration.setFont(new java.awt.Font("Lucida Grande", 0, 13)); // NOI18N
        btnProfessorRegistration.setText("Professor Sign up");
        btnProfessorRegistration.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnProfessorRegistrationActionPerformed(evt);
            }
        });

        btnStudentSignup.setFont(new java.awt.Font("Lucida Grande", 0, 13)); // NOI18N
        btnStudentSignup.setText("Student Sign up");
        btnStudentSignup.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnStudentSignupActionPerformed(evt);
            }
        });

        lblNewStudent.setFont(new java.awt.Font("Lucida Grande", 0, 13)); // NOI18N
        lblNewStudent.setForeground(new java.awt.Color(255, 255, 255));
        lblNewStudent.setText("New Student");

        lblSignUp.setFont(new java.awt.Font("Lucida Grande", 1, 18)); // NOI18N
        lblSignUp.setForeground(new java.awt.Color(255, 255, 255));
        lblSignUp.setText("Sign Up");

        txtPassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPasswordActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout ActionPanelLayout = new javax.swing.GroupLayout(ActionPanel);
        ActionPanel.setLayout(ActionPanelLayout);
        ActionPanelLayout.setHorizontalGroup(
            ActionPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ActionPanelLayout.createSequentialGroup()
                .addGroup(ActionPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(ActionPanelLayout.createSequentialGroup()
                        .addGroup(ActionPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(ActionPanelLayout.createSequentialGroup()
                                .addGap(30, 30, 30)
                                .addComponent(btnLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(ActionPanelLayout.createSequentialGroup()
                                .addGap(47, 47, 47)
                                .addComponent(lblSignUp)))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(ActionPanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(ActionPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtUserName)
                            .addGroup(ActionPanelLayout.createSequentialGroup()
                                .addGroup(ActionPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(lblUserName, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblNewStudent, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btnStudentSignup, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(btnProfessorRegistration, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(lblNewProfessor, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ActionPanelLayout.createSequentialGroup()
                                        .addComponent(lblLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(30, 30, 30)))
                                .addGap(0, 11, Short.MAX_VALUE))
                            .addComponent(txtPassword))))
                .addContainerGap())
        );

        ActionPanelLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {lblLogin, lblPassword, lblUserName});

        ActionPanelLayout.setVerticalGroup(
            ActionPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ActionPanelLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(lblLogin)
                .addGap(18, 18, 18)
                .addComponent(lblUserName)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtUserName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lblPassword)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnLogin)
                .addGap(72, 72, 72)
                .addComponent(lblSignUp)
                .addGap(18, 18, 18)
                .addComponent(lblNewProfessor)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnProfessorRegistration)
                .addGap(18, 18, 18)
                .addComponent(lblNewStudent)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnStudentSignup)
                .addContainerGap(184, Short.MAX_VALUE))
        );

        SplitHomeArea.setLeftComponent(ActionPanel);

        workAreaPanel.setBackground(new java.awt.Color(0, 153, 255));
        workAreaPanel.setForeground(new java.awt.Color(0, 153, 255));
        workAreaPanel.setLayout(new java.awt.CardLayout());

        jLabel1.setFont(new java.awt.Font("Lucida Grande", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("DIGITAL EDUCATIONAL PLATFORM");
        workAreaPanel.add(jLabel1, "card2");

        SplitHomeArea.setRightComponent(workAreaPanel);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(SplitHomeArea, javax.swing.GroupLayout.DEFAULT_SIZE, 800, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(SplitHomeArea)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtUserNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtUserNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtUserNameActionPerformed

    private void btnProfessorRegistrationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnProfessorRegistrationActionPerformed
        // TODO add your handling code here:
        ProfessorRegistrationJPanel professorRegistrationPanel = new ProfessorRegistrationJPanel(workAreaPanel, business);
        workAreaPanel.add("ProfessorRegistrationJPanel",professorRegistrationPanel);
        CardLayout layout = (CardLayout) workAreaPanel.getLayout();
        layout.next(workAreaPanel);
    }//GEN-LAST:event_btnProfessorRegistrationActionPerformed

    private void btnStudentSignupActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnStudentSignupActionPerformed
        // TODO add your handling code here:
        StudentRegistrationJPanel studentRegistrationPanel = new StudentRegistrationJPanel(workAreaPanel, business);
        workAreaPanel.add("StudentRegistrationJPanel",studentRegistrationPanel);
        CardLayout layout = (CardLayout) workAreaPanel.getLayout();
        layout.next(workAreaPanel);
    }//GEN-LAST:event_btnStudentSignupActionPerformed

    private void btnLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLoginActionPerformed
        // TODO add your handling code here:
        String username = txtUserName.getText();
        String password = "";
        char[] pwd =txtPassword.getPassword();
        for(char c: pwd){
            System.out.print(c);
           password += c;
       }
        System.out.println();
        if(username.equals("")){
           JOptionPane.showMessageDialog(null,"Please enter username");
           return;
        }
        if(password.equals((""))){
           JOptionPane.showMessageDialog(null,"Please enter password");
           return; 
        }
        UserAccountDirectory userAccountList = business.getUserAccountList();
       // System.out.println(userAccountList.AuthenticateUser(username, password));
       UserAccount userAccount = userAccountList.searchUserAccount(username);
       if(userAccount == null){
           JOptionPane.showMessageDialog(null,"UserAccount with username: "+ username+" doesn't exist. Please register");
           return;           
       }
       CourseDirectory courseList = business.getCourseList();
        if(userAccountList.AuthenticateUser(userAccount, password)){
            ProfessorWorkAreaJPanel professorWorkAreaPanel;
            AdminWorkAreaJPanel adminWorkAreaJPanel;
            StudentWorkAreaJPanel studentWorkAreaPanel;
            String role = userAccount.getRole();
            CardLayout layout;
            if(role.equals("Faculty")){
                JOptionPane.showMessageDialog(null,"Welcome "+userAccount.getProfessorProfile().getPerson().getPersonName());
                ProfessorProfile professor = userAccount.getProfessorProfile();
                professorWorkAreaPanel = new ProfessorWorkAreaJPanel(workAreaPanel,userAccount,business);
                workAreaPanel.add("ProfessorWorkAreaJPanel",professorWorkAreaPanel);
                layout = (CardLayout) workAreaPanel.getLayout();
                layout.next(workAreaPanel); 
            }
            if(role.equals("Student")){
                JOptionPane.showMessageDialog(null,"Welcome "+userAccount.getStudentProfile().getPerson().getPersonName());
                studentWorkAreaPanel = new StudentWorkAreaJPanel(workAreaPanel, userAccount, business);
                workAreaPanel.add("StudentWorkAreaJPanel",studentWorkAreaPanel);
                layout = (CardLayout) workAreaPanel.getLayout();
                layout.next(workAreaPanel);
            }
            if(role.equals("Admin")){
                JOptionPane.showMessageDialog(null,"Welcome "+userAccount.getEmployeeProfile().getPerson().getPersonName());
                adminWorkAreaJPanel = new AdminWorkAreaJPanel(workAreaPanel, business);
                workAreaPanel.add("AdminWorkAreaJPanel",adminWorkAreaJPanel);
                layout = (CardLayout) workAreaPanel.getLayout();
                layout.next(workAreaPanel);
            }
        }
        else{
            JOptionPane.showMessageDialog(null, "Invalid User or Password");
        }
    }//GEN-LAST:event_btnLoginActionPerformed

    private void txtPasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPasswordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPasswordActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ProfileWorkAreaMainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ProfileWorkAreaMainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ProfileWorkAreaMainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ProfileWorkAreaMainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ProfileWorkAreaMainJFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel ActionPanel;
    private javax.swing.JSplitPane SplitHomeArea;
    private javax.swing.JButton btnLogin;
    private javax.swing.JButton btnProfessorRegistration;
    private javax.swing.JButton btnStudentSignup;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel lblLogin;
    private javax.swing.JLabel lblNewProfessor;
    private javax.swing.JLabel lblNewStudent;
    private javax.swing.JLabel lblPassword;
    private javax.swing.JLabel lblSignUp;
    private javax.swing.JLabel lblUserName;
    private javax.swing.JPasswordField txtPassword;
    private javax.swing.JTextField txtUserName;
    private javax.swing.JPanel workAreaPanel;
    // End of variables declaration//GEN-END:variables
}
