/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package UserInterface.workArea.Professor;

import Business.Business;
import Business.Course.StudentCourseDirectory;
import Business.Course.StudentCourseStatus;
import Business.Course.StudentCourses;
import Business.UserAccounts.UserAccount;
import java.awt.CardLayout;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author Darshil Shah
 */
public class ProfessorProfileJPanel extends javax.swing.JPanel {

    /**
     * Creates new form ProfessorProfileJPanel
     */JPanel workAreaPanel;
     UserAccount userAccount;
     Business business;
    public ProfessorProfileJPanel(JPanel workAreaProfile, UserAccount userAccount, Business business) {
        initComponents();
        this.workAreaPanel = workAreaProfile;
        this.userAccount = userAccount;
        this.business = business;
        populateDetails();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtProfessorName = new javax.swing.JTextField();
        lblProfessorID = new javax.swing.JLabel();
        txtProfessorID = new javax.swing.JTextField();
        lblUsername = new javax.swing.JLabel();
        txtUsername = new javax.swing.JTextField();
        lblPassword = new javax.swing.JLabel();
        txtPassword = new javax.swing.JTextField();
        lblProfessorName = new javax.swing.JLabel();
        lblProfessorProfile = new javax.swing.JLabel();
        btnSave = new javax.swing.JButton();
        btnUpdate = new javax.swing.JButton();
        btnBack = new javax.swing.JButton();
        lblRating = new javax.swing.JLabel();
        txtrRating = new javax.swing.JTextField();
        lblLanguage = new javax.swing.JLabel();
        lblRegion = new javax.swing.JLabel();
        lblSpecialization = new javax.swing.JLabel();
        cbRegion = new javax.swing.JComboBox<>();
        cbSpecialization = new javax.swing.JComboBox<>();
        cbLanguage = new javax.swing.JComboBox<>();

        setBackground(new java.awt.Color(51, 153, 255));
        setEnabled(false);

        txtProfessorName.setFont(new java.awt.Font("Lucida Grande", 0, 13)); // NOI18N
        txtProfessorName.setForeground(new java.awt.Color(255, 255, 255));
        txtProfessorName.setEnabled(false);
        txtProfessorName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtProfessorNameActionPerformed(evt);
            }
        });

        lblProfessorID.setFont(new java.awt.Font("Lucida Grande", 0, 13)); // NOI18N
        lblProfessorID.setForeground(new java.awt.Color(255, 255, 255));
        lblProfessorID.setText("Professor ID");

        txtProfessorID.setFont(new java.awt.Font("Lucida Grande", 0, 13)); // NOI18N
        txtProfessorID.setForeground(new java.awt.Color(255, 255, 255));
        txtProfessorID.setEnabled(false);
        txtProfessorID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtProfessorIDActionPerformed(evt);
            }
        });

        lblUsername.setFont(new java.awt.Font("Lucida Grande", 0, 13)); // NOI18N
        lblUsername.setForeground(new java.awt.Color(255, 255, 255));
        lblUsername.setText("Username");

        txtUsername.setFont(new java.awt.Font("Lucida Grande", 0, 13)); // NOI18N
        txtUsername.setForeground(new java.awt.Color(255, 255, 255));
        txtUsername.setEnabled(false);
        txtUsername.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtUsernameActionPerformed(evt);
            }
        });

        lblPassword.setFont(new java.awt.Font("Lucida Grande", 0, 13)); // NOI18N
        lblPassword.setForeground(new java.awt.Color(255, 255, 255));
        lblPassword.setText("Password");

        txtPassword.setFont(new java.awt.Font("Lucida Grande", 0, 13)); // NOI18N
        txtPassword.setEnabled(false);
        txtPassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPasswordActionPerformed(evt);
            }
        });

        lblProfessorName.setFont(new java.awt.Font("Lucida Grande", 0, 13)); // NOI18N
        lblProfessorName.setForeground(new java.awt.Color(255, 255, 255));
        lblProfessorName.setText("Professor Name");

        lblProfessorProfile.setFont(new java.awt.Font("Lucida Grande", 1, 18)); // NOI18N
        lblProfessorProfile.setForeground(new java.awt.Color(255, 255, 255));
        lblProfessorProfile.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblProfessorProfile.setText("Professor Profile");

        btnSave.setFont(new java.awt.Font("Lucida Grande", 0, 13)); // NOI18N
        btnSave.setText("Save");
        btnSave.setEnabled(false);
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });

        btnUpdate.setFont(new java.awt.Font("Lucida Grande", 0, 13)); // NOI18N
        btnUpdate.setText("Update");
        btnUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateActionPerformed(evt);
            }
        });

        btnBack.setText("<< Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });

        lblRating.setFont(new java.awt.Font("Lucida Grande", 0, 13)); // NOI18N
        lblRating.setForeground(new java.awt.Color(255, 255, 255));
        lblRating.setText("Rating");

        txtrRating.setFont(new java.awt.Font("Lucida Grande", 0, 13)); // NOI18N
        txtrRating.setForeground(new java.awt.Color(255, 255, 255));
        txtrRating.setEnabled(false);
        txtrRating.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtrRatingActionPerformed(evt);
            }
        });

        lblLanguage.setFont(new java.awt.Font("Lucida Grande", 0, 13)); // NOI18N
        lblLanguage.setForeground(new java.awt.Color(255, 255, 255));
        lblLanguage.setText("Language");

        lblRegion.setFont(new java.awt.Font("Lucida Grande", 0, 13)); // NOI18N
        lblRegion.setForeground(new java.awt.Color(255, 255, 255));
        lblRegion.setText("Region");

        lblSpecialization.setFont(new java.awt.Font("Lucida Grande", 0, 13)); // NOI18N
        lblSpecialization.setForeground(new java.awt.Color(255, 255, 255));
        lblSpecialization.setText("Specialization");

        cbRegion.setFont(new java.awt.Font("Lucida Grande", 0, 13)); // NOI18N
        cbRegion.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Asia-Pacific", "America", "Europe", "Australia", "Africa", "South-East Asia" }));
        cbRegion.setEnabled(false);
        cbRegion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbRegionActionPerformed(evt);
            }
        });

        cbSpecialization.setFont(new java.awt.Font("Lucida Grande", 0, 13)); // NOI18N
        cbSpecialization.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "DAMG", "INFO", "CSYE", "DS", "IE", "DAE" }));
        cbSpecialization.setEnabled(false);

        cbLanguage.setFont(new java.awt.Font("Lucida Grande", 0, 13)); // NOI18N
        cbLanguage.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "English", "Spanish", "Mandarin", "French", "Korean" }));
        cbLanguage.setEnabled(false);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(btnBack)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(lblProfessorProfile, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(158, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(lblUsername, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtUsername, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(lblProfessorName, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtProfessorName, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(lblSpecialization)
                                .addComponent(lblPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(lblRating, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(txtPassword)
                                .addComponent(txtrRating)
                                .addComponent(cbSpecialization, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(lblProfessorID, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtProfessorID, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(lblLanguage)
                                .addComponent(lblRegion))
                            .addGap(90, 90, 90)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(cbRegion, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(cbLanguage, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addComponent(btnSave)
                        .addGap(46, 46, 46)
                        .addComponent(btnUpdate)))
                .addGap(152, 152, 152))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(lblProfessorProfile, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnBack)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblProfessorName)
                    .addComponent(txtProfessorName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblProfessorID)
                    .addComponent(txtProfessorID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblUsername)
                    .addComponent(txtUsername, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblPassword)
                    .addComponent(txtPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtrRating, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblRating))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblSpecialization)
                    .addComponent(cbSpecialization, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblRegion)
                    .addComponent(cbRegion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblLanguage)
                    .addComponent(cbLanguage, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(19, 19, 19)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnUpdate)
                    .addComponent(btnSave))
                .addContainerGap(212, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void txtProfessorNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtProfessorNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtProfessorNameActionPerformed

    private void txtProfessorIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtProfessorIDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtProfessorIDActionPerformed

    private void txtUsernameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtUsernameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtUsernameActionPerformed

    private void txtPasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPasswordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPasswordActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:
        workAreaPanel.remove(this);
        CardLayout layout = (CardLayout)workAreaPanel.getLayout();
        layout.previous(workAreaPanel);
                
    }//GEN-LAST:event_btnBackActionPerformed

    private void txtrRatingActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtrRatingActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtrRatingActionPerformed

    private void btnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateActionPerformed
        // TODO add your handling code here:
        btnSave.setEnabled(true);
        txtPassword.setEnabled(true);
        txtPassword.setText(userAccount.getPassword());
        cbSpecialization.setEnabled(true);
        cbRegion.setEnabled(true);
        cbLanguage.setEnabled(true);
        
        
        btnUpdate.setEnabled(false);   
    }//GEN-LAST:event_btnUpdateActionPerformed

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
        // TODO add your handling code here:
        btnUpdate.setEnabled(true);
        
        txtPassword.setEnabled(false);
        btnSave.setEnabled(false);
        cbSpecialization.setEnabled(false);
        cbRegion.setEnabled(false);
        cbLanguage.setEnabled(false);
        
        String password =txtPassword.getText();
        if(password.equals("")){
           JOptionPane.showMessageDialog(null,"Please enter password");
           populateDetails();
           return;             
        }
        userAccount.setPassword(password);
        if(cbRegion.getSelectedItem() == null){
           JOptionPane.showMessageDialog(null,"Please select Region from list");
           populateDetails();
           return;            
        }
        userAccount.getProfessorProfile().setRegion(cbRegion.getSelectedItem().toString());
        if(cbSpecialization.getSelectedItem() == null){
          JOptionPane.showMessageDialog(null,"Please select specializatoin from list");
          populateDetails();
          return;  
        }
        userAccount.getProfessorProfile().setSpecialization(cbSpecialization.getSelectedItem().toString());
        if(cbLanguage.getSelectedItem() == null){
          JOptionPane.showMessageDialog(null,"Please select Language from list");
          populateDetails();
          return;  
        }        
        userAccount.getProfessorProfile().setLanguage(cbLanguage.getSelectedItem().toString());
        JOptionPane.showMessageDialog(null,"Account updated");
    }//GEN-LAST:event_btnSaveActionPerformed

    private void cbRegionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbRegionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbRegionActionPerformed
    public void populateDetails(){
        calculateRating();
        txtProfessorName.setText(userAccount.getProfessorProfile().getPerson().getPersonName());
        txtProfessorID.setText(Integer.toString(userAccount.getProfessorProfile().getPerson().getPersonId()));
        txtrRating.setText(Double.toString(userAccount.getProfessorProfile().getRating()));
        cbSpecialization.setSelectedItem(userAccount.getProfessorProfile().getSpecialization());
        cbRegion.setSelectedItem(userAccount.getProfessorProfile().getRegion());
        cbLanguage.setSelectedItem(userAccount.getProfessorProfile().getLanguage());
        txtUsername.setText(userAccount.getUsername());
        txtPassword.setText(userAccount.getPassword());
    }
    
    public void calculateRating(){
        double rating = 0;
        int counter = 1;
         StudentCourseDirectory studentCourseList = business.getStudentCoursesList();
         for(StudentCourses studentCourses: studentCourseList.getStudentCourseList()){
             for(StudentCourseStatus studentCourseStatus:studentCourses.getStudentCourses()){
                 if(studentCourseStatus.getStudentBrowseCourses().getProfessor() == userAccount.getProfessorProfile()){
                     rating += studentCourseStatus.getProffesorRating();
                     counter += 1;
                 }
             }
         }
         rating = (rating/counter);
         userAccount.getProfessorProfile().setRating(rating);
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnSave;
    private javax.swing.JButton btnUpdate;
    private javax.swing.JComboBox<String> cbLanguage;
    private javax.swing.JComboBox<String> cbRegion;
    private javax.swing.JComboBox<String> cbSpecialization;
    private javax.swing.JLabel lblLanguage;
    private javax.swing.JLabel lblPassword;
    private javax.swing.JLabel lblProfessorID;
    private javax.swing.JLabel lblProfessorName;
    private javax.swing.JLabel lblProfessorProfile;
    private javax.swing.JLabel lblRating;
    private javax.swing.JLabel lblRegion;
    private javax.swing.JLabel lblSpecialization;
    private javax.swing.JLabel lblUsername;
    private javax.swing.JTextField txtPassword;
    private javax.swing.JTextField txtProfessorID;
    private javax.swing.JTextField txtProfessorName;
    private javax.swing.JTextField txtUsername;
    private javax.swing.JTextField txtrRating;
    // End of variables declaration//GEN-END:variables
}
