/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package UserInterface.workArea.Professor;

import Business.Business;
import Business.Course.CourseDirectory;
import Business.UserAccounts.UserAccount;
import java.awt.CardLayout;
import javax.swing.JPanel;

/**
 *
 * @author Darshil Shah
 */
public class ProfessorWorkAreaJPanel extends javax.swing.JPanel {

    /**
     * Creates new form ProfessorWorkAreaJPanel
     */
    JPanel workAreaPanel; 
    UserAccount userAccount;
    CourseDirectory courseList;
    Business business;
    public ProfessorWorkAreaJPanel(JPanel workAreaPanel, UserAccount userAccount, Business business) {
        initComponents();
        this.workAreaPanel = workAreaPanel;
        this.userAccount = userAccount;
        this.business = business;
        this.courseList = business.getCourseList();
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnProfessorProfile = new javax.swing.JButton();
        lblProfessorWorkArea = new javax.swing.JLabel();
        btnManageCourses = new javax.swing.JButton();
        btnManageStudent = new javax.swing.JButton();

        setBackground(new java.awt.Color(51, 153, 255));

        btnProfessorProfile.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        btnProfessorProfile.setText("My Profile");
        btnProfessorProfile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnProfessorProfileActionPerformed(evt);
            }
        });

        lblProfessorWorkArea.setFont(new java.awt.Font("Lucida Grande", 1, 18)); // NOI18N
        lblProfessorWorkArea.setForeground(new java.awt.Color(255, 255, 255));
        lblProfessorWorkArea.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblProfessorWorkArea.setText("Professor WorkArea");

        btnManageCourses.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        btnManageCourses.setText("Manage Courses");
        btnManageCourses.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnManageCoursesActionPerformed(evt);
            }
        });

        btnManageStudent.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        btnManageStudent.setText("Manage Student");
        btnManageStudent.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnManageStudentActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 212, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnManageStudent, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnManageCourses, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnProfessorProfile, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(210, 210, 210))
            .addComponent(lblProfessorWorkArea, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(lblProfessorWorkArea, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(46, 46, 46)
                .addComponent(btnProfessorProfile)
                .addGap(18, 18, 18)
                .addComponent(btnManageCourses)
                .addGap(18, 18, 18)
                .addComponent(btnManageStudent)
                .addContainerGap(392, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnManageCoursesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnManageCoursesActionPerformed
        // TODO add your handling code here:
       ProfessorManageCoursesjPanel professorManageCoursesPanel = new ProfessorManageCoursesjPanel(workAreaPanel,userAccount,business);
       workAreaPanel.add("ProfessorManageCoursesjPanel",professorManageCoursesPanel);
       CardLayout layout = (CardLayout) workAreaPanel.getLayout();
       layout.next(workAreaPanel);
    }//GEN-LAST:event_btnManageCoursesActionPerformed

    private void btnProfessorProfileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnProfessorProfileActionPerformed
        // TODO add your handling code here:
       ProfessorProfileJPanel professorProfileJPanel = new ProfessorProfileJPanel(workAreaPanel, userAccount, business);
       workAreaPanel.add("ProfessorWorkAreaJPanel",professorProfileJPanel);
       CardLayout layout = (CardLayout) workAreaPanel.getLayout();
       layout.next(workAreaPanel); 
    }//GEN-LAST:event_btnProfessorProfileActionPerformed

    private void btnManageStudentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnManageStudentActionPerformed
        // TODO add your handling code here:
       ProfessorManageStudentJPanel professorManagerStudentPanel = new ProfessorManageStudentJPanel(workAreaPanel,userAccount, business);
       workAreaPanel.add("ProfessorManageStudentJPanel",professorManagerStudentPanel);
       CardLayout layout = (CardLayout) workAreaPanel.getLayout();
       layout.next(workAreaPanel);
    }//GEN-LAST:event_btnManageStudentActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnManageCourses;
    private javax.swing.JButton btnManageStudent;
    private javax.swing.JButton btnProfessorProfile;
    private javax.swing.JLabel lblProfessorWorkArea;
    // End of variables declaration//GEN-END:variables
}
