/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package UserInterface.workArea.Professor;

import Business.Business;
import Business.Course.StudentBrowseCourses;
import Business.Course.StudentCourseDirectory;
import Business.Course.StudentCourseStatus;
import Business.Course.StudentCourses;
import Business.Profiles.StudentDirectory;
import Business.Profiles.StudentProfile;
import Business.UserAccounts.UserAccount;
import java.awt.CardLayout;
import java.awt.event.KeyEvent;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Darshil Shah
 */
public class ProfessorManageStudentJPanel extends javax.swing.JPanel {

    /**
     * Creates new form ProfessorManageStudentJPanel
     */
    JPanel workAreaPanel;
    Business business;
    UserAccount userAccount;
    StudentCourseDirectory studentCourseList;
    StudentDirectory studentList;
    StudentCourses studentCourses;
            
    public ProfessorManageStudentJPanel(JPanel workAreaPanel, UserAccount userAccount, Business business) {
        initComponents();
        this.workAreaPanel = workAreaPanel;
        this.userAccount = userAccount;
        this.business = business;
        this.studentCourseList = business.getStudentCoursesList(); 
        this.studentList = business.getStudentList();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        lblStudentId = new javax.swing.JLabel();
        txtStudentId = new javax.swing.JTextField();
        btnSearch = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblStudentStatus = new javax.swing.JTable();
        cbCourseStatus = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        btnSave = new javax.swing.JButton();
        btnBack = new javax.swing.JButton();

        setBackground(new java.awt.Color(51, 153, 255));
        setForeground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("Lucida Grande", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Manage Student");

        lblStudentId.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        lblStudentId.setForeground(new java.awt.Color(255, 255, 255));
        lblStudentId.setText("Student Id");

        txtStudentId.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtStudentIdKeyPressed(evt);
            }
        });

        btnSearch.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        btnSearch.setText("Search");
        btnSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchActionPerformed(evt);
            }
        });

        tblStudentStatus.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        tblStudentStatus.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Student Name", "Course Id", "Course Name", "Status"
            }
        ));
        jScrollPane1.setViewportView(tblStudentStatus);

        cbCourseStatus.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        cbCourseStatus.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "In Progress", "Completed" }));
        cbCourseStatus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbCourseStatusActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Course Status");

        btnSave.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        btnSave.setText("Save");
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });

        btnBack.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        btnBack.setText("<< Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(btnBack)
                .addGap(265, 265, 265)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(259, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnSave, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cbCourseStatus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblStudentId, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtStudentId, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnSearch))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 671, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(59, 59, 59))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(btnBack))
                .addGap(54, 54, 54)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblStudentId)
                    .addComponent(txtStudentId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSearch))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 388, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 30, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbCourseStatus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(18, 18, 18)
                .addComponent(btnSave)
                .addGap(114, 114, 114))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:
        workAreaPanel.remove(this);
        CardLayout layout = (CardLayout)workAreaPanel.getLayout();
        layout.previous(workAreaPanel);
    }//GEN-LAST:event_btnBackActionPerformed

    private void btnSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchActionPerformed
        // TODO add your handling code here:
        if((txtStudentId.getText()).equals("")){
           JOptionPane.showMessageDialog(null,"Please enter Student Id to search");
           return;   
        }
        int studentId = Integer.parseInt(txtStudentId.getText());
        System.out.println(studentId);
        StudentProfile student = studentList.findStudent(studentId);
        if(student == null){
           JOptionPane.showMessageDialog(null,"No student with student Id: "+studentId+" found");
           return;  
        }
        System.out.println(student);
        this.studentCourses = studentCourseList.findStudentCourses(student);
        populateStudentTable(studentCourses);
        
    }//GEN-LAST:event_btnSearchActionPerformed

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(null,"Student information saved.");
        return; 
    }//GEN-LAST:event_btnSaveActionPerformed

    private void cbCourseStatusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbCourseStatusActionPerformed
        // TODO add your handling code here:
        int selectedRowIndex = tblStudentStatus.getSelectedRow();
        if(selectedRowIndex<0){
            JOptionPane.showMessageDialog(this,"Please select row from Course Catalog to delete");
            return;
        }
        DefaultTableModel dtm = (DefaultTableModel) tblStudentStatus.getModel();
        //String status= (String) dtm.getValueAt(selectedRowIndex, 3);
        StudentCourseStatus studentCourseStatus = (StudentCourseStatus) dtm.getValueAt(selectedRowIndex, 3);
        System.out.println(studentCourseStatus.getCourseStatus());
        String status = cbCourseStatus.getSelectedItem().toString();
        System.out.println(status);
        studentCourseStatus.setCourseStatus(status);
        populateStudentTable(studentCourses);
        
      
    }//GEN-LAST:event_cbCourseStatusActionPerformed

    private void txtStudentIdKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtStudentIdKeyPressed
        // TODO add your handling code here:
        int digit = evt.getKeyChar();
        if(!((digit>='0' && digit <= '9')||evt.getExtendedKeyCode()== KeyEvent.VK_BACK_SPACE)){
            JOptionPane.showMessageDialog(null,"Please enter only digits");      
        }
    }//GEN-LAST:event_txtStudentIdKeyPressed
  public void populateStudentTable(StudentCourses studentCourses){
       DefaultTableModel dtm = (DefaultTableModel) tblStudentStatus.getModel();
       dtm.setRowCount(0);
       for(StudentCourseStatus studentCourseStatus: studentCourses.getStudentCourses()){
           if(studentCourseStatus.getStudentBrowseCourses().getProfessor() == userAccount.getProfessorProfile()){
                Object row[]= new Object[4];
                row[0] = studentCourses.getStudent().getPerson().getPersonName();
                row[1] = studentCourseStatus.getStudentBrowseCourses();
                row[2] = studentCourseStatus.getStudentBrowseCourses().getCourseSemester().getCourse().getCourseName();
                row[3] = studentCourseStatus;
                dtm.addRow(row);
           }         
       }
}

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnSave;
    private javax.swing.JButton btnSearch;
    private javax.swing.JComboBox<String> cbCourseStatus;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblStudentId;
    private javax.swing.JTable tblStudentStatus;
    private javax.swing.JTextField txtStudentId;
    // End of variables declaration//GEN-END:variables
}


